// Food Stories for Casa Mexico - Mexican Cuisine Education

export interface FoodStory {
  id: string;
  slug: string;
  title: string;
  titleSpanish: string;
  category: string;
  excerpt: string;
  content: string;
  author: string;
  date: string;
  readTime: string;
  image: string;
  type: 'article' | 'video';
  videoUrl?: string;
  tags: string[];
}

export const foodStories: FoodStory[] = [
  // RECIPE HISTORY
  {
    id: '1',
    slug: 'history-of-tacos',
    title: 'The Ancient Origins of Tacos',
    titleSpanish: 'Los Orígenes Antiguos de los Tacos',
    category: 'Recipe History',
    excerpt: 'From ancient Aztec silver mines to street food phenomenon - the fascinating journey of Mexico\'s most iconic dish.',
    content: 'Tacos date back to 18th century Mexican silver mines...',
    author: 'Casa Mexico Team',
    date: '2024-12-15',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80',
    type: 'article',
    tags: ['Tacos', 'History', 'Mexican Culture'],
  },
  {
    id: '2',
    slug: 'story-of-mole',
    title: 'Mole: The Sacred Sauce of Mexico',
    titleSpanish: 'Mole: La Salsa Sagrada de México',
    category: 'Recipe History',
    excerpt: 'Discover the legendary origin of mole - a complex sauce with over 20 ingredients that defines Mexican cuisine.',
    content: 'The story of mole begins in Puebla...',
    author: 'Casa Mexico Team',
    date: '2024-12-10',
    readTime: '10 min read',
    image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=800&q=80',
    type: 'article',
    tags: ['Mole', 'History', 'Puebla'],
  },
  {
    id: '3',
    slug: 'origins-of-margarita',
    title: 'The Margarita: Mexico\'s Cocktail Legacy',
    titleSpanish: 'La Margarita: El Legado de México',
    category: 'Recipe History',
    excerpt: 'Uncover the disputed origins of the world\'s most popular tequila cocktail.',
    content: 'Several stories claim to be the true origin...',
    author: 'Casa Mexico Team',
    date: '2024-12-01',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
    type: 'article',
    tags: ['Margarita', 'Cocktails', 'History'],
  },

  // COOKING TIPS
  {
    id: '4',
    slug: 'perfect-guacamole',
    title: 'The Art of Perfect Guacamole',
    titleSpanish: 'El Arte del Guacamole Perfecto',
    category: 'Cooking Tips',
    excerpt: 'Master the secrets to creating creamy, flavorful guacamole that keeps everyone coming back.',
    content: 'Choose perfectly ripe avocados...',
    author: 'Casa Mexico Team',
    date: '2024-11-28',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1619897603729-f8a523994c0e?w=800&q=80',
    type: 'article',
    tags: ['Guacamole', 'Technique', 'Appetizers'],
  },
  {
    id: '5',
    slug: 'homemade-tortillas-video',
    title: 'Making Tortillas from Scratch (Video)',
    titleSpanish: 'Tortillas Hechas a Mano',
    category: 'Cooking Tips',
    excerpt: 'Watch our chefs demonstrate the traditional technique for making fresh corn and flour tortillas.',
    content: 'Video tutorial on tortilla making...',
    author: 'Casa Mexico Team',
    date: '2024-11-25',
    readTime: '15 min',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80',
    type: 'video',
    videoUrl: 'https://youtube.com/watch?v=example',
    tags: ['Tortillas', 'Technique', 'Video'],
  },
  {
    id: '6',
    slug: 'grilling-carne-asada',
    title: 'Secrets to Perfect Carne Asada',
    titleSpanish: 'Secretos de la Carne Asada Perfecta',
    category: 'Cooking Tips',
    excerpt: 'Learn the marinade secrets and grilling techniques for tender, flavorful carne asada.',
    content: 'The key is in the marinade and high heat...',
    author: 'Casa Mexico Team',
    date: '2024-11-20',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1599974768596-e345fc3a0daf?w=800&q=80',
    type: 'article',
    tags: ['Carne Asada', 'Grilling', 'Technique'],
  },

  // HEALTH & NUTRITION
  {
    id: '7',
    slug: 'health-benefits-cilantro',
    title: 'The Powerful Health Benefits of Cilantro',
    titleSpanish: 'Beneficios del Cilantro',
    category: 'Health & Nutrition',
    excerpt: 'Discover why this essential Mexican herb is packed with vitamins, antioxidants, and healing properties.',
    content: 'Cilantro has been used medicinally for centuries...',
    author: 'Casa Mexico Team',
    date: '2024-11-15',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1618897996318-5a901fa6ca71?w=800&q=80',
    type: 'article',
    tags: ['Cilantro', 'Health', 'Herbs'],
  },
  {
    id: '8',
    slug: 'avocado-superfood',
    title: 'Why Avocados are a Superfood',
    titleSpanish: 'Aguacate: Superalimento',
    category: 'Health & Nutrition',
    excerpt: 'Learn about the nutritional powerhouse that makes Mexican cuisine so healthy and delicious.',
    content: 'Avocados are rich in healthy fats...',
    author: 'Casa Mexico Team',
    date: '2024-11-10',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800&q=80',
    type: 'article',
    tags: ['Avocado', 'Health', 'Nutrition'],
  },
  {
    id: '9',
    slug: 'beans-and-health',
    title: 'The Nutritional Power of Mexican Beans',
    titleSpanish: 'El Poder Nutricional de los Frijoles',
    category: 'Health & Nutrition',
    excerpt: 'Explore why beans are a cornerstone of healthy Mexican cooking and their impressive health benefits.',
    content: 'Beans provide protein, fiber, and essential nutrients...',
    author: 'Casa Mexico Team',
    date: '2024-11-05',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1596040033229-a0b3b1fea2b8?w=800&q=80',
    type: 'article',
    tags: ['Beans', 'Health', 'Protein'],
  },

  // FOOD CULTURE
  {
    id: '10',
    slug: 'dia-de-muertos-foods',
    title: 'Day of the Dead Traditional Foods',
    titleSpanish: 'Comida del Día de Muertos',
    category: 'Food Culture',
    excerpt: 'Discover the symbolic foods and their meanings in this beautiful Mexican tradition.',
    content: 'Pan de muerto and sugar skulls...',
    author: 'Casa Mexico Team',
    date: '2024-12-20',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=800&q=80',
    type: 'article',
    tags: ['Day of the Dead', 'Culture', 'Traditions'],
  },
  {
    id: '11',
    slug: 'tequila-culture',
    title: 'Tequila: From Agave to Glass',
    titleSpanish: 'Tequila: Del Agave al Vaso',
    category: 'Food Culture',
    excerpt: 'Journey through the traditional process of making Mexico\'s national spirit.',
    content: 'Tequila production is an art form...',
    author: 'Casa Mexico Team',
    date: '2024-11-30',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
    type: 'article',
    tags: ['Tequila', 'Spirits', 'Culture'],
  },
  {
    id: '12',
    slug: 'mexican-table-traditions',
    title: 'Mexican Dining Traditions & Etiquette',
    titleSpanish: 'Tradiciones de la Mesa Mexicana',
    category: 'Food Culture',
    excerpt: 'Learn the customs and etiquette of traditional Mexican family dining.',
    content: 'Mexican meals are about family and community...',
    author: 'Casa Mexico Team',
    date: '2024-11-22',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80',
    type: 'article',
    tags: ['Etiquette', 'Traditions', 'Culture'],
  },

  // SEASONAL SPECIALS
  {
    id: '13',
    slug: 'summer-ceviches',
    title: 'Fresh Summer Ceviches',
    titleSpanish: 'Ceviches Frescos de Verano',
    category: 'Seasonal Specials',
    excerpt: 'Cool down with refreshing ceviches featuring the season\'s best seafood.',
    content: 'Summer is perfect for light, citrusy ceviches...',
    author: 'Casa Mexico Team',
    date: '2024-12-18',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    type: 'article',
    tags: ['Ceviche', 'Summer', 'Seafood'],
  },
  {
    id: '14',
    slug: 'winter-pozole',
    title: 'Warming Winter Pozole',
    titleSpanish: 'Pozole Caliente de Invierno',
    category: 'Seasonal Specials',
    excerpt: 'Traditional Mexican hominy soup perfect for cold winter days.',
    content: 'Pozole has been warming souls for centuries...',
    author: 'Casa Mexico Team',
    date: '2024-11-12',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=800&q=80',
    type: 'article',
    tags: ['Pozole', 'Winter', 'Soup'],
  },
  {
    id: '15',
    slug: 'spring-chiles',
    title: 'Spring Chiles and Fresh Salsas',
    titleSpanish: 'Chiles y Salsas de Primavera',
    category: 'Seasonal Specials',
    excerpt: 'Celebrate spring with fresh chiles and vibrant green salsas.',
    content: 'Spring brings the freshest chiles...',
    author: 'Casa Mexico Team',
    date: '2024-11-08',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1618897996318-5a901fa6ca71?w=800&q=80',
    type: 'article',
    tags: ['Chiles', 'Salsa', 'Spring'],
  },

  // CHEF'S SECRETS
  {
    id: '16',
    slug: 'perfect-rice-and-beans',
    title: 'The Secret to Perfect Mexican Rice & Beans',
    titleSpanish: 'Secreto del Arroz y Frijoles Perfectos',
    category: "Chef's Secrets",
    excerpt: 'Our chef reveals the techniques for fluffy rice and creamy beans that complete every meal.',
    content: 'The secret is in toasting the rice first...',
    author: 'Casa Mexico Team',
    date: '2024-12-05',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
    type: 'article',
    tags: ['Rice', 'Beans', 'Technique'],
  },
  {
    id: '17',
    slug: 'marinating-meats',
    title: 'Marinating Techniques for Maximum Flavor',
    titleSpanish: 'Técnicas de Marinado',
    category: "Chef's Secrets",
    excerpt: 'Learn the art of marinating meats for tacos, fajitas, and carne asada.',
    content: 'Proper marinating transforms the meat...',
    author: 'Casa Mexico Team',
    date: '2024-11-18',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1599974768596-e345fc3a0daf?w=800&q=80',
    type: 'article',
    tags: ['Marinating', 'Meat', 'Technique'],
  },
  {
    id: '18',
    slug: 'making-salsa-video',
    title: 'Making Fresh Salsa from Scratch (Video)',
    titleSpanish: 'Haciendo Salsa Fresca',
    category: "Chef's Secrets",
    excerpt: 'Watch our chef create three essential Mexican salsas - salsa roja, verde, and pico de gallo.',
    content: 'Video demonstration of salsa making...',
    author: 'Casa Mexico Team',
    date: '2024-11-14',
    readTime: '12 min',
    image: 'https://images.unsplash.com/photo-1618897996318-5a901fa6ca71?w=800&q=80',
    type: 'video',
    videoUrl: 'https://youtube.com/watch?v=example',
    tags: ['Salsa', 'Video', 'Technique'],
  },
  {
    id: '19',
    slug: 'selecting-chiles',
    title: 'A Guide to Mexican Chiles',
    titleSpanish: 'Guía de Chiles Mexicanos',
    category: "Chef's Secrets",
    excerpt: 'Learn to identify and use different Mexican chiles - from mild poblanos to fiery habaneros.',
    content: 'Each chile has unique flavor and heat...',
    author: 'Casa Mexico Team',
    date: '2024-11-03',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1583535522463-11a0d4345974?w=800&q=80',
    type: 'article',
    tags: ['Chiles', 'Ingredients', 'Guide'],
  },

  // COOKING TIPS (Additional)
  {
    id: '20',
    slug: 'tortilla-basics',
    title: 'Corn vs Flour Tortillas: When to Use Each',
    titleSpanish: 'Tortillas de Maíz vs Harina',
    category: 'Cooking Tips',
    excerpt: 'Understand the difference between corn and flour tortillas and which dishes pair best with each.',
    content: 'Corn tortillas are traditional for tacos...',
    author: 'Casa Mexico Team',
    date: '2024-10-28',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80',
    type: 'article',
    tags: ['Tortillas', 'Basics', 'Guide'],
  },
];

export const categories = [
  'All',
  'Recipe History',
  'Cooking Tips',
  'Health & Nutrition',
  'Food Culture',
  'Seasonal Specials',
  "Chef's Secrets",
];

export const getStoriesByCategory = (category: string) => {
  if (category === 'All') return foodStories;
  return foodStories.filter(story => story.category === category);
};

export const getStoryBySlug = (slug: string) => {
  return foodStories.find(story => story.slug === slug);
};

export default foodStories;
